### PR TITLE
Moving navbar to a separate css and adding blocks around links

### PR DESCRIPTION
**Pull request by Ankitasingh88**
Moving navbar to a separate css and adding blocks around links
The color pallete around navlinks we can change when we have agreed on a color theme

### CODE REVIEW

**Review by PriyeshIllam — APPROVED** [review]
Looking good to me

**Review by PriyeshIllam — APPROVED** [review]
LGTM

**Comment by VaishaliGovindaraj** [comment]
Great work ankita :)  looks good  to me

**Review by VaishaliGovindaraj — APPROVED** [review]
Great work

**Comment by Ankitasingh88** [comment]
Merging changes

**Pull request merged**
