### PR TITLE
Feature/layout

### PR DESCRIPTION
**Pull request by VaishaliGovindaraj**
Please do code review for the below changes

1. On mobile , sidebar and main content should look good on all smaller screen.
2. Page should not break for sidebar and main content * Header needs mobile query , please ignore header)

### CODE REVIEW

**Review by PriyeshIllam — APPROVED** [review]
LGTM

**Comment by Ankitasingh88** [comment]
it seems good to me

**Review by Ankitasingh88 — APPROVED** [review]
looks good for me

**Comment by VaishaliGovindaraj** [comment]
confirming the layout changes for mobile queries in Sidebar, main content in home page

**Pull request merged**
